version: '3.9'

services:
  db:
    image: postgres:15
    container_name: django_postgres
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django123
      POSTGRES_DB: django_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: